DNA = "TCCGGCCTATTAGGAGAGTCCTGTCGGTAGCAATTGATACCGTCCAAATGGAGCCTAGTTTCACAGACTGTGGCTGCGGCTTATGATTGATATCAATTGCGGCGTTATTCGCTATCCATTGTGCATTGGGACATTCTCAGAGTGTCTCGTAGTCCATTCTAGTTGGCGTTATTCCGGGTAAGCCATAGATATCAGACGAAAGCCGGGTCCCATTCTGTGCCTAGTAGGTACGGGAAACGCCGCTAAGTATAACTACGTCTAAAAACCAAGCTGATTGCTCATCAGGCTGTACCTTAATAAAGGACGTTGCACGGAACAGTGGAGCAGAAGCCTCCTCGTCCAAAGTCTGAGAACCTCTGCAGGATTTCGTGAAATTTCCGCTGGAACCTTTTTGGTGATATCGTAGTGACACTTTGTCTGTTTGAAGCGCCAGCACAAGAGATCCTTGATCGTCTGCGCAGCCGTTTGGGCTGCGCGGGTATATTTTTATGACGTTTGTGACCCCAAGAATCTGCTATAGTACTCTTAGGTAATTGCGAGTATGCTATGTGACCTATAATTATCCCCCCCCCCTCATCAAACTTACCGTCGTGTTGAGGGTAGGAGTCAAAAGGATCTCTCCGTCGATTCCTGCGCTACCTCGACCCCACTAAATGGTATCCGTGAACCGTTCGTGGATGGAGCGCTTAGTCTTTCGTAAATACGCGCTTGGTAAACGAAGCCTTTATTGGTTGAGCACATTCAGTTGCGGAGTGTATGCACCAGCTTGTAGTAAAATTGATAAATCGAAAGTAGCTGCGCGGCAATTTCGTGAATGTAAGTAAATCTGCGAAGGTAGCTTTACGACGA"

DNAbases = list(DNA)
DNAbases.reverse()
print(DNAbases)

cDNA = " "

for nucleotide in DNAbases:
    if nucleotide == "A":
        cDNA += "T"
    elif nucleotide == "T":
        cDNA += "A"
    elif nucleotide == "G":
        cDNA += "C"
    elif nucleotide == "C":
        cDNA += "G"
    
print(cDNA)

#had a problem with the if "A" - figured out, but have to look at a few things