DNA_bases = 'GTGCCGTGGCGATAGCTTCGCCTTCGTGCGGAGGGCTCTAATCATGTCCCGAATTCAAAATAGAAGCCCTCCCCATCGAGGATTCGGGGGGCCAGGGGATAGTTCACGGCGTGGCATCAGAAAGAGGAAGATAAGCCCGTGAAGGGCGAAGCGATTACCTACCAGTGTTTGCATTAGACACTTGGGCTATGGATGCCCTCACATTGTCTATGGTATTATGCAAGTGGCTCGTGGCAATCGATCCAAAAACGAATCTAGTCGGCGGGTAAGAACGCCCATATACGGCTTGTGTAAAACCTATAGTAATGTCTACGTTATTATTTCCAAGAGAACTAAAGGAGTTCTCTTACTTTTTTAAGGCGCTATCTTCTTCAGTGCACTAGTCTCACGAAGTCTCATAATCAGGCATCGACATTTCCGCCACATCAAGTCAGTAACTATAAGATGGGTTCATGAGTAGGCGTCATGCGGCATAATACTTTGCCCAGCTAGGAGGTCAGCTCCTGATTGATCAACCCAAGATCCGTTGGCACAACTCACTGTGGTGGGTGATGCAGACTACCTTGTAGCAAGCCAAACGTCTTGCCGGTATTCTACTTACTGATCAAAACGGAGCATTGATGGGGCCCAAGCCTACCTCGCTGGGATACGAGGTGTTGCCAATGGATGATAGCGTGTCCGATACTTACGTACACAGCTATTTGTCTTCAGCGGGGAACATTTTCTTCCGGCCAAATACCGTTGGCACCTGAGGACCGGTTCGCTTGCGAATTAGCGCTGCGCCGCGGCATGTCCCCCTGGTTTTAAATGTAGACCCGTGGTTATATTGAGGCTAGCCTTGTCCGCTCGTCTATCTTGTGGTCATGGTCCTCCTC'

# Create a dictionary to store nucleotide counts
nucleotides_count = {'A': 0, 'C': 0, 'G': 0, 'T': 0}

# Iterate through each nucleotide in the DNA sequence
for nucleotide in DNA_bases:
    # Increment the count of the current nucleotide
    nucleotides_count[nucleotide] += 1

# Print the count of each nucleotide in the specified order
for nucleotide in ['A', 'C', 'G', 'T']:
    print(nucleotide + ':', nucleotides_count[nucleotide])